### ISSUE TITLE
More Traits Specialization bug? XP multiplier disappearing 

### ISSUE THREAD

**Issue by jbells37** [hypnotoadtrance/MoreTraits#14]
For some reason I’m running into an issue where if you choose Specialization: Gun your XP multiplier from reading books for the main crafts (carpentry, metalworking, mechanics etc.) will disappear after gaining XP. Anyone else?

**Comment by jbells37** [comment]
*after reading a book like Carpentry Vol.1  (if you go gain XP in carpentry) The multiplier for carpentry will disappear.

**Comment by jbells37** [comment]
Even if it says it has been read in Training materials.

**Comment by Xenu47** [comment]
Issue was resolved in https://github.com/hypnotoadtrance/MoreTraits/commit/d47443a9e4bf1d6bc3fc8e88276ac28b548bb98a

Will be available in game with next workshop update

**Comment by hypnotoadtrance** [comment]
as Xenu mentioned, this issue was resolved and is pending release to Steam.
