### ISSUE TITLE
Questions about the trait : "Unwavering"

### ISSUE THREAD

**Issue by Surgeol** [hypnotoadtrance/MoreTraits#148]
The description of Unwavering said that "`You recover from zombie attacks twice as fast`".

But according to my test this feature only work in some specific case.

<details>
<summary>Here are some examples</summary>

### Back side test(not work)
![back side](https://user-images.githubusercontent.com/35412032/217448254-2d82a448-18da-425a-8120-d30b41e14505.gif)
### Front side test(not work)
![front side](https://user-images.githubusercontent.com/35412032/217448265-acb2a2e7-854a-4dc5-a15d-5e9c77d5ecf2.gif)
### Left and right side test(work, but with some animation issues)
![left and right side](https://user-images.githubusercontent.com/35412032/217448267-60bcfac5-bc61-44aa-bbca-38af17e9f05b.gif)
</details>

I'm not sure if this is a bug or deliberately designed.

**Comment by Fajdek** [comment]
Hello.
I tested a few minutes ago and my tests resulted in Unwavering activating 100% of the time.
However, it only activated when my player character took damage. Turning off god mod fixed this issue.
I've tried with bare hands and weapon equipped from multiple angles and they always activated.
Did you have god mod enabled when testing?

**Comment by Surgeol** [comment]
Ah yes, I test that with debug mode, I didn't expect god mode will lead to those things.
Thank you!
