### ISSUE TITLE
Helo: need “Depressive” and “selfdestructive” for mi mod “i am legend”

### ISSUE THREAD

**Issue by Iluviathar** [hypnotoadtrance/MoreTraits#150]
I want to isolate the code from the "depressive" and "self-destructive" traits but I can't separate it from the functioning of the other traits. If I remove extra things, the mod stops working or gets damaged. If I delete lines of code below those traits the mod stops working, the trait exists but has no real function, it is as if the line was not executed. But if I delete lines before that, the mod works correctly. I would really like to get a version of only those 2 features working.
I try to create a mod that emulates the behavior of the character from Richard Matheson's original book. For that I have created a profession called "Robert Neville", his own starter kit and clothing, and a feature that adds certain recipes and statistics. That part of the mod was easy for me to create. But to emulate the psychology of the character I would like to be able to take the aforementioned features and modify their values and names, so that they work through my traits instead of those of your mod, but maintaining their structure and functionality.
If you could provide me with a version of the moretrait. If it contained only the lines necessary for the functioning of "depressive" and "self-destructive", I would greatly appreciate it. Or explain to me how to do it myself. I would give you the authorship of the mod if you wish, since I am not interested in credit, just give the community the possibility of playing with the character of "I am a legend" as imagined by its creator, with a single click.

**Comment by hypnotoadtrance** [comment]
Because the functions in question are so interwoven and rely on several aspects of More Trait's code and global variables, it would be beyond my inclination to trim out and rectify the code.

The best I can tell you is to examine the functions:
MainPlayerUpdate
ToadTraitDepressive
CheckDepress
CheckSelfHarm

To see how the code runs through them in action.

Best wishes to you.
