### ISSUE TITLE
Evasive Procs on Bandaging Wounds

### ISSUE THREAD

**Issue by hypnotoadtrance** [hypnotoadtrance/MoreTraits#19]
Need to add checks that prevent this.
The code uses the 
BodyPart.scratched(), .bitten(), .isCut() methods to retrieve if a body part is wounded. I would think that scratched() returns true even if the wound is bandaged, but apparently this is triggering Evasive again.

**Comment by milosxv2** [comment]
I have only seen bug happen when taking bandages off a wound
. When the bug happens the wound is "Dogged" and disappears from the body "Instantly Heals". This bug appears not to affect: Burns and Fractures. But even these wounds can be "Instantly Healed" if there is a wound other than previous two already on a affected spot I.E. ( Scratch ). To replicate the bug simply take off a bandage of a affected area couple of times and the bug will eventually proc.
![Dogged_All_but_Fracture](https://user-images.githubusercontent.com/93518885/148962597-5799df2a-2619-4845-9aff-99851084d9c6.png)
![Guinea_Pig](https://user-images.githubusercontent.com/93518885/148962605-aee45334-3c2b-4511-b9be-4f7515c62d05.png)
![How_bug_Happens](https://user-images.githubusercontent.com/93518885/148962611-8a6c72df-0729-490f-80a3-d163db241231.png)
![Mods_Used](https://user-images.githubusercontent.com/93518885/148962618-8169c35f-76c4-41da-b24a-2276a2dd8fde.png)
![Traits_Used](https://user-images.githubusercontent.com/93518885/148962622-d7d24544-0c6f-4a90-a250-ce61d0c73ce5.png)
