### ISSUE TITLE
Martial scaling

### ISSUE THREAD

**Issue by Wyghab** [hypnotoadtrance/MoreTraits#40]
In the description of martial scaling, a value of 50 (half) should reduce damage to half. But in actuality it is reduced by more. This is because average fitness&strength has scaling applied twice. Fixing it is simple, just thought I'd let you know when I had a quick look over the code for the trait. It's way more impactful with values above 100, as it is multiplicative.

> local function martial(_actor, _target, _weapon, _damage)
>     local SmallBluntLvl = player:getPerkLevel(Perks.SmallBlunt);
>     local StrengthLvl = player:getPerkLevel(Perks.Strength);
>     local Fitnesslvl = player:getPerkLevel(Perks.Fitness);
>     local average = ((StrengthLvl + Fitnesslvl) / 2) * scaling; // Can simply remove the scaling from here to "fix" if unintended.
>     local minimumdmg = (0.1 * average + SmallBluntLvl * 0.1) * scaling; // Average gets factored twice by scaling
>     local maximumdmg = (0.5 * average + SmallBluntLvl * 0.1) * scaling;

**Comment by hypnotoadtrance** [comment]
Forgot to mention this scaling issue was resolved in the latest patch.
Closing issue.
