### ISSUE TITLE
Would it be possible to add an option for "More Description for Traits" style specific information?

### ISSUE THREAD

**Issue by JohnEdwa** [hypnotoadtrance/MoreTraits#42]
It would be very helpful if for example instead of the: "You drive cars much more effectively. Vehicles move faster, make less noise, and handle more efficiently.", it could tell the exact numbers and factors in use as MDfT does for Speed Demon: 
"The fast driver. (+100% gear switching speed, +15% top speed for all vehicles, +200% engine loudness when reversing.)",  
And while indeed it would make sense for MDfT to add them instead, as a ton of the MoreTraits stuff is sandbox customizable I'm not sure if it would be feasible?

The reasoning for this was that I suggested adding MoreTraits to our MP server, and as we use MDfT, I was immediately swamped with questions about the exact numbers and effects. Especially as our plan would be to eventually add the updated Dynamic Traits as well, it's going to get confusing fast.

**Comment by hypnotoadtrance** [comment]
This would be something for the creator of MDfT to address.
