### ISSUE TITLE
Bug with Thuggish trait localization

### ISSUE THREAD

**Issue by bendingbender1** [hypnotoadtrance/MoreTraits#62]
I play with russian localization. If on new character creation i first choose brawler(-6) trait, then thuggish trait(-5) disappear. But instead i can pick second brawler trait(-6), and both are +1 Axe and +1 Long blunt. If pick thuggish first, then brawler - all working without problem. Russian translation of thuggis and brawler are same:
```
UI_trait_blunttwirl = "Хулиган"
UI_trait_BarFighter = "Хулиган"
```
I suggest change translation to "Бандит", its more accurate translation of thuggish. When I manualy change line to 
`UI_trait_blunttwirl = "Бандит"`
character creation working without problem.

**Comment by hypnotoadtrance** [comment]
Thanks for pointing this out and providing a solution. 
I'll implement this change and have it put out in the next update. :)
