### ISSUE TITLE
Gym-Goer bonus XP

### ISSUE THREAD

**Issue by Xenu47** [hypnotoadtrance/MoreTraits#8]
Gym-Goer gives **+200% XP, while doing anything** to increase your strength/fitness, not just exercising. 

Judging from [trait](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/shared/Translate/EN/UI_EN.txt#L135) and [sandbox](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/shared/Translate/EN/Sandbox_EN.txt#L28) descriptions, trait should work as follows:

> Exercise is twice as effective for you

[1902](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L1902) does not guatantee player is getting XP just from excersising. 

Possible partial fix: check if player is moving by checking `player:getPlayerMoveDir():getLength()` - returns player [movement vector](https://theindiestone.com/zomboidjavadocs/zombie/characters/IsoPlayer.html#getPlayerMoveDir())'s [length](https://theindiestone.com/zomboidjavadocs/zombie/iso/Vector2.html#getLength()), which equals 0 while standing or 0.5 while moving. 
Fix is partial because player will still get bonus XP from [killing zombies](https://pzwiki.net/wiki/Skills#Passives) while standing still.

[1903-1904](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L1903-L1904) gives **additional** 200% XP (default modifier) to [already gained XP](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L1953).

Fix: either removing already gained XP like in [Specialization](https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L707) and then adding XP with already existing code or changing https://github.com/hypnotoadtrance/MoreTraits/blob/e139c9a441c56b64bc343da690a9847f93fe9ea1/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L1903 to `amount = amount * (modifier - 1)`.

Tested in single player debugging, entered this into console: 
`function a(_player,_perk,_amount)local player=_player;local perk=_perk;local amount=_amount;if perk == Perks.Fitness or perk == Perks.Strength then player:Say(string.format("%s", amount)) end end Events.AddXP.Add(a)` - player says how much XP he got to Str/Fit, had to be one continious line :(
Sprinted around a bit holding Alt, player said 3 times he got 1 XP, checked my total Fitness XP = 9 = 3 + 3*2 (+200% instead of just x2, 200%)
Hitting zombies with bare hands also gave me XP, as it should lol. Pushing and making zombie fall gave 1XP to Fit, 1XP to Str and 2XP tp Str, yes, 1+2, not 3, anyway my stats became: Fit = 3; Str = 9; | 3 times more than they should

Idk how I got here from translating Sandbox_EN.txt XD

**Comment by hypnotoadtrance** [comment]
Unfortunately, there's no way to distinguish between sources of Xp. Fitness XP gained from running/fighting is the same function as Xp gained from exercising.

Unfortunately, while the check getPlayer():isPlayerMoving() might be one way to isolate the Xp source, since fitness xp is given at later time after exercising, this could result in the player not receiving the extra Xp.

At present, I don't have a way to determine where the Xp originated, so this will have to remain an open issue.
