### ISSUE TITLE
Grave Robber Chance

### ISSUE THREAD

**Issue by SivWatt** [hypnotoadtrance/MoreTraits#98]
I found that if you have trait `scrounger`, it will increase the possibility that `grave robber` happens. 
However, I think they should be independent since they are two traits and there is no explanation about their relationship.
I understand that `scrounger` also happens on dead bodies, but the chance of each other should be calculated individually. 

[Here is the code](https://github.com/hypnotoadtrance/MoreTraits/blob/master/Contents/mods/More%20Traits/media/lua/client/MoreTraits.lua#L2689-L2691)

**Comment by hypnotoadtrance** [comment]
You raise a fair argument. I myself like having these hidden values throughout code. Letting other traits have slight effects on others for this invisible interplay that makes for varied effects.

I will confer with others on the Discord and see what the general opinion is.

**Comment by SivWatt** [comment]
> You raise a fair argument. I myself like having these hidden values throughout code. Letting other traits have slight effects on others for this invisible interplay that makes for varied effects.
> 
> I will confer with others on the Discord and see what the general opinion is.

It's nice to know your core concept of design.

**Comment by hypnotoadtrance** [comment]
Closing this issue, as the consensus was made these minor bonuses are not necessary to be explained on trait descriptions - this is something that could be saved for More Trait Descriptions mod instead, if desired.
